'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import SectionNav from '@/components/SectionNav';
import ChecklistSection from '@/components/ChecklistSection';
import TimelineSection from '@/components/TimelineSection';

export default function Home() {
  const [activeSection, setActiveSection] = useState<'checklist' | 'timeline'>('checklist');

  return (
    <div className="min-h-screen">
      <SectionNav activeSection={activeSection} onSectionChange={setActiveSection} />
      
      <AnimatePresence mode="wait">
        {activeSection === 'checklist' ? (
          <motion.div
            key="checklist"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            transition={{ duration: 0.3 }}
          >
            <ChecklistSection />
          </motion.div>
        ) : (
          <motion.div
            key="timeline"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <TimelineSection />
          </motion.div>
        )}
      </AnimatePresence>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8 mt-16">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="text-gray-400 mb-2">
            Generated by <strong className="text-accent-400">Columbus</strong> • Your Full-Cycle AI Travel Advisor
          </p>
          <p className="text-sm text-gray-500">
            Utrecht ⇄ Zakopane • Dec 13 – Dec 28, 2025
          </p>
        </div>
      </footer>
    </div>
  );
}



